pipeline {
    agent any        
    stages {
        stage('Checkout-git'){            
            steps{
                echo 'Reviewing Project Prasenjit repository'
                git poll: true, url: 'https://github.com/PrasenjitM9/Jenkinsfile-maven-junit.git'
            } 
        }    
        stage('Build') {
            steps {
		//bat 'C:\\maven-3.6.2\\bin\\mvn -B -DskipTests clean package'
		bat 'mvn clean package'
//                sh 'mvn -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
		bat 'mvn test'
                //sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
		echo 'Deploy del jar'
		bat 'java -jar target/my-app-1.0-SNAPSHOT.jar --httpPort=8080'
		//sh 'java -jar target/my-app-1.0-SNAPSHOT.jar --httpPort=8082'
               bat './jenkins/scripts/deliver.sh'
            }
        }
    }
}

